from llm_sdk import Small_LLM_Model  # type: ignore[attr-defined]
import json
from src.utility_function import select_token_for_function_name
from src.utility_function import trim_function_names
from src.utility_function import select_token_by_type
from typing import Any
from enum import Enum


class GenerationStep(Enum):
    """Enumerates the steps of the main generation loop."""

    OPEN_STRUCTURE = 1
    FUNCTION_NAME = 2
    OPEN_PARAMETERS = 3
    ARGUMENTS = 4


def generate_function_call(prompt: dict[str, Any], model: Small_LLM_Model,
                           _function: list[dict[str, Any]],
                           vocabulary: dict[int, str],
                           name_function: list[str]) -> dict[str, Any]:
    """Generate a validated function call JSON using constrained decoding.

    The output is built token by token through a state machine driven
    by GenerationStep. Fixed structural tokens (braces, keys,
    separators) are injected directly, while the function name and
    argument values are generated by the model under type-specific
    constraints to guarantee schema-compliant, valid JSON.

    Args:
        prompt: The validated prompt dictionary to process.
        model: The language model used to generate logits.
        _function: List of available function definitions.
        vocabulary: Mapping of token IDs to their string representation.
        name_function: List of candidate function names.

    Returns:
        A dictionary representing the generated function call, with
        keys "prompt", "name", and "parameters".
    """

    structure: list[int] = []
    prompt_text = json.dumps(prompt['prompt'])[1:-1]
    first_structure = f"{{\"prompt\": \"{prompt_text}\",\"name\": \""
    third_structure = ",\"parameters\": "

    tensor = model.encode(f"Functions: {json.dumps(_function)}. "
                          f"Choose the BEST matching function "
                          "for this request. "
                          f"Request: {prompt_text}. "
                          f"Answer with the function name that best matches."
                          " the description. choose parameters with the request.")

    input_ids = tensor[0].tolist()

    str_function_name = ""
    index_function = 0
    len_arguments = 0
    keys_and_types: list[tuple[str, str]] = []
    count_args = 0
    zero_arg = False

    def emit_text(text: str) -> None:
        """Encode a fixed text segment and append it to ids/structure."""

        ids = model.encode(text)[0].tolist()
        input_ids.extend(ids)
        structure.extend(ids)

    def emit_token(token_id: int) -> None:
        """Append a single generated token to ids/structure."""

        input_ids.append(int(token_id))
        structure.append(int(token_id))

    step = GenerationStep.OPEN_STRUCTURE
    while True:
        if step == GenerationStep.OPEN_STRUCTURE:
            emit_text(first_structure)
            step = GenerationStep.FUNCTION_NAME

        if step == GenerationStep.FUNCTION_NAME:

            next_token = select_token_for_function_name(
                input_ids, vocabulary, name_function, model)
            str_token = model.decode(next_token)
            if str_token.endswith('"'):
                if str_token.startswith('"'):
                    emit_text('"')
                else:
                    emit_token(next_token)
                step = GenerationStep.OPEN_PARAMETERS
                continue
            else:
                str_function_name += str_token
            emit_token(next_token)

            name_function = [x for x in name_function
                             if x.startswith(str_token)]
            name_function = trim_function_names(len(str_token),
                                                name_function)

        if step == GenerationStep.OPEN_PARAMETERS:
            emit_text(third_structure)

            for d in _function:
                if d['name'] == str_function_name:
                    break
                index_function += 1
            for k, v in _function[index_function]['parameters'].items():
                keys_and_types.append((k, v['type']))
                len_arguments += 1
            if len_arguments == 0:
                zero_arg = True

            step = GenerationStep.ARGUMENTS

        if step == GenerationStep.ARGUMENTS:
            if count_args == len_arguments and zero_arg:
                emit_text("{")
                emit_text("}")
                emit_text("}")
                break
            if count_args == len_arguments:
                emit_text("}")
                emit_text("}")
                break

            key_arg = f"{{\"{keys_and_types[count_args][0]}\": "
            if count_args > 0:
                key_arg = f"\"{keys_and_types[count_args][0]}\": "
            key_or_value = "key"
            type_arg = keys_and_types[count_args][1]

            while True:

                if key_or_value == "key":
                    emit_text(key_arg)
                    key_or_value = "value"

                if key_or_value == "value":

                    if type_arg == "integer":
                        next_token = select_token_by_type(
                            input_ids, vocabulary,
                            model, "number", tuple("0123456789")
                            )
                        decode_token = model.decode(int(next_token))

                        if decode_token.startswith('0'):
                            emit_token(next_token)
                        else:
                            len_integer = 0
                            while decode_token.startswith(
                                    tuple("0123456789")):
                                if len_integer == 11:
                                    break
                                emit_token(next_token)
                                next_token = select_token_by_type(
                                    input_ids, vocabulary,
                                    model, "number", tuple("0123456789},")
                                    )
                                decode_token = model.decode(next_token)
                                len_integer += 1
                        count_args += 1

                    if type_arg == 'number':
                        next_token = select_token_by_type(
                            input_ids, vocabulary,
                            model, "number", tuple("0123456789")
                            )
                        decode_tok = model.decode(int(next_token))

                        if decode_tok.startswith('0'):
                            emit_token(next_token)
                            next_token = select_token_by_type(
                                input_ids, vocabulary,
                                model, "number", tuple(".},")
                                )
                            decode_tok = model.decode(next_token)
                            if decode_tok.startswith('.'):
                                emit_token(next_token)
                                next_token = select_token_by_type(
                                    input_ids, vocabulary,
                                    model, "number", tuple("0123456789")
                                    )
                                decode_tok = model.decode(next_token)
                                while decode_tok.startswith(
                                        tuple("0123456789")):
                                    emit_token(next_token)
                                    next_token = select_token_by_type(
                                        input_ids, vocabulary,
                                        model, "number", tuple("0123456789},")
                                        )
                                    decode_tok = model.decode(next_token)
                            else:
                                emit_text('.')
                                emit_text('0')
                        else:
                            point = 0
                            while decode_tok.startswith(
                                    tuple("0123456789.")):
                                if decode_tok.startswith('.'):
                                    point += 1
                                emit_token(next_token)
                                next_token = select_token_by_type(
                                    input_ids, vocabulary,
                                    model, "number", tuple("0123456789.},")
                                    )
                                decode_tok = model.decode(next_token)
                            if point == 0:
                                emit_text('.')
                                emit_text('0')
                        count_args += 1

                    if type_arg == 'string':
                        next_token = select_token_by_type(
                            input_ids, vocabulary, model, "quotes"
                            )
                        emit_token(next_token)

                        max_string_tokens = 35
                        string_token_count = 0
                        while True:
                            string_token_count += 1
                            if string_token_count > max_string_tokens:
                                next_token = select_token_by_type(
                                    input_ids, vocabulary, model, "quotes"
                                    )
                                emit_token(next_token)
                                break

                            next_token = select_token_by_type(
                                input_ids, vocabulary, model, "string"
                                )
                            decode_token = model.decode(int(next_token))
                            if (decode_token.endswith('"')):
                                if (decode_token.startswith('"')
                                        or decode_token.endswith('\\"')):
                                    next_token = select_token_by_type(
                                        input_ids, vocabulary, model, "quotes"
                                        )
                                    emit_token(next_token)
                                    break
                                else:
                                    emit_token(next_token)
                                    break
                            emit_token(next_token)
                        count_args += 1
                    if type_arg == 'boolean':
                        next_token = select_token_by_type(
                            input_ids, vocabulary, model, "boolean"
                            )
                        emit_token(next_token)
                        count_args += 1

                    if type_arg == 'none':
                        emit_text("null")
                        count_args += 1

                    if count_args < len_arguments:
                        emit_text(",")
                    break
    dict_structure: dict[str, Any] = json.loads(model.decode(structure))
    return dict_structure
